### ISSUE TITLE
furtherInformationURL attribute redundant?

### ISSUE THREAD

**Issue by thill-odi** [openactive/routes#1]
Is this needed? Should the route encapsulate all the information making this attribute redundant?

**Comment by croesus** [comment]
I think there will always be the potential for information outside the schema, especially related to marketing and promotions, so this would seem a good way to allow for that

**Comment by blabyboy** [comment]
I'd opt for removing it. What do you do if there are more than one marketing/promotion/other URLs that are relevant? The URLs should be confined within the Description for a Route which can be edited by the Publisher as required and published back out to the feed.

**Comment by thill-odi** [comment]
This is a tricky one: I think the scope for related material is indeed large. First, there's the issue of marketing and promotions, as @croesus mentions. And then there are a fair number of organisations for which the Route material is an addendum to other concerns (e.g. the RSPB - https://www.rspb.org.uk/reserves-and-events/reserves-a-z/trumland - where the Route is really just one aspect of the wildlife reserve). This means that the chances of more than one URL being relevant are quite high.

This leaves a few options, I think:

1.  Put everything in the Description field, as @blabyboy suggests
2. Make the datatype for the furtherInformationURL more complex, so that it can be multivalued and take e.g. a 'label' property indicating the nature or text of the link
3. Narrow the focus of furtherInformationURL, so that we have e.g. a contextualInformationURL, a marketingInformationURL, etc.

I think on balance I'd like to opt for a variant on 3, whereby furtherInformationURL is scoped down to originatingSiteURL or similar - basically, a means of linking back to the site where the Route was initially defined. Then the originating organisation can populate *that* with marketing or additional material as appropriate, and the function of the link can be defined precisely.

I'm less keen on 1 because of likely publishing workflows. While we definitely need to support hand-curation of Routes data, we have to anticipate that a lot of it is going to come from some sort of automated harvesting process, and I'm not sure we can rely upon manual editing too heavily in the first instance.

I don't like 2 because it starts getting complicated.

**Comment by thill-odi** [comment]
Implemented as `oa:originatingPublisher`: https://www.openactive.io/modelling-opportunity-data/EditorsDraft#describing-route-metadata-oa-routemetadata-.
