### ISSUE TITLE
Segmenting Routes

### ISSUE THREAD

**Issue by thill-odi** [openactive/routes#10]
Routes are often broken down for practical and descriptive purposes into subsections, which will here be described as 'segments'. This is particularly the case for 'waypoint' guides and styles of navigation, whereby the Route is broken down into a series of numbered stages to be traversed in succession (e.g. the National Trust's [Sycamore Gap walk](https://www.nationaltrust.org.uk/hadrians-wall-and-housesteads-fort/trails/sycamore-gap-walk)).

The proposal here is to support such waypoint-style segmentation by the creation of a Segment datatype in the specification. The Segment data model as proposed is exactly the same as the Routes data-model, with the following exceptions:

1. Each Segment has a mandatory attribute, 'sequence', which consists of an integer. These integers must be consecutive, and indicate the order of the Segments along the route.
2. If a Route has Segments at all, it must have at least two Segments.
3. The first Segment must begin at the startPoint of the Route as a whole
4. The last Segment must end at the endPoint of the Route as a whole
5. Segments may not themselves contain Segments

**Comment by thill-odi** [comment]
Issue raised on call 17 July: there's a potential problem here with redundancy and duplication. For example, if a Route can be joined at multiple points, do we define a startPoint on each segment, or an array of startPoints on the parent Route? Presumably these examples could be multiplied. Some thought will need to be given about what other attributes may diverge in this way.

**Comment by thill-odi** [comment]
Note with regard to Mandatory/Recommended/Optional attributes on segments: implicitly, attributes defined at the Route level are inherited by Segments, so everything on individual segments should be Optional, with the exception of `sequence` and `description` (Mandatory), and 'startPoint' (Recommended).

**Comment by croesus** [comment]
I wonder whether we should adopt OpenStreetMap's terminology of "ways" rather than "segments". We would also inherit some excellent mapping tools if we build upon their schema. Good intro here:
https://labs.mapbox.com/mapping/

**Comment by thill-odi** [comment]
I think this is really about the limitations/scope of the spec itself (see https://github.com/openactive/routes/issues/13), and I wonder if the fact that OSM uses 'ways' isn't in fact an argument *against* using it here. AFAICT, for OSM, a 'way' is a quite low-level geo type - any line connecting nodes, basically, which can then be tagged as desired to provide further information. 'Segments' here, however, may exist independently of any geo representation (as you'll see if you look at the [Sycamore Gap](https://www.nationaltrust.org.uk/hadrians-wall-and-housesteads-fort/trails/sycamore-gap-walk) example).

Ideally I think we would eventually have annotatable geo files for as many routes as possible, and we might want to map back and forth between information in this specification and information in the (say) OSM file - and it's at this point that I start to get a little chary about the 'ways' terminology, because we would then end up mapping between **oa:ways** and **osm:ways** - and while avoiding ambiguity here is what namespaces are for, I don't think we're making our lives any easier here.

That said, I'm in fact borrowing the 'segments' terminology from @blabyboy, who might have some thoughts here.

**Comment by thill-odi** [comment]
See https://www.openactive.io/modelling-opportunity-data/EditorsDraft#segmenting-routes-routes-as-a-collection-of-sub-routes

**Comment by abs0** [comment]
Many of the other characteristics listed (safety #11, restrictions #6, suitability #9, even events #12, and accessibility #16) can vary wildly across the segments of a route. 

While embedding segments in routes keeps things simple I'm concerned that it may be insufficiently flexible over time. An alternative would be a hierarchical model where a segment has the sequence integer and the URI of another route to define its data.

This would still allow a route to be split into segments without affecting any existing references to it, and allow users to easily construct "meta-routes"

**Comment by thill-odi** [comment]
Okay, `@id` and `alternativeSegmentTo` attributes have been added to the spec to allow cross- and unique-referencing in the way described by @abs0.

**Comment by thill-odi** [comment]
`alternativeSegmentTo` now renamed as `alternativeRouteSegmentMetadata`.
