### ISSUE TITLE
What should the subject of the standard be called? Routes? RouteMetadata? RouteGuidance? RouteGuide?

### ISSUE THREAD

**Issue by thill-odi** [openactive/routes#13]
A persistent issue with this specification is the extent to which it's a specification *of* geo entities (in the same way that, say, GeoJSON or the Open Street Map data model are fundamentally concerned with geo issues), or whether it might better be termed a metadata standard *about* a geo entity.

The nature of route-related publication 'in the wild' (see the [Routes data-exploration matrix](https://docs.google.com/spreadsheets/d/12hAkSB9OP3snzzRj9TKwod-1yVYRECkLBk4garIWDPw/edit#gid=0) means that at this stage I think we're necessarily concerned with metadata: many publishers do not provide GIS files for their routes at all, and the geo information is represented by, e.g. a PDF or .jpg file. At times even this is rudimentary, and route information is provided largely in a 'wayfinding', text-based file.

The proposal, then, is to indicate this functional focus by naming the spec Routes Metadata, rather than simply Routes. This paves the way to developing a Routes specification proper later in the year, where we can concern ourselves with the geo entities themselves.

The distinction is to some extent artificial - one can imagine in many cases mapping fields from Routes Metadata to Routes via e.g. OSM annotations. But the change in name should make the functional scope and limitations of the specification clear.

**Comment by thill-odi** [comment]
Implemented in current Editors Draft: see https://www.openactive.io/modelling-opportunity-data/EditorsDraft, section 5.13

**Comment by thill-odi** [comment]
After various debates, RouteMetadata was renamed to RouteGuidance. However, this reformulation has also been criticised, and the alternative 'RouteGuide' has been proposed. The countering arguments are:
* 'RouteGuidance' might be taken to imply a much closer and more continuous form of guidance (possibly step-by-step) being given. If what's actually being modelled is, essentially, a guidebook, then 'RouteGuide' is a better name
* OTOH, people may have very concrete expectations of what a guidebook consists of, and may thus be surprised if a 'RouteGuide' contains, e.g., dynamic route-generation properties but lacks, say, information about points of interest and historical background.

**Comment by awoods-NT** [comment]
We opened this question out to the wider team at a recent meeting – one suggestion was to perhaps name the standard ‘RouteInformation’. The thoughts are this is encompasses the areas of routes the standard is modelling (route context, geographic information etc.) without being too technical a term when sharing the standard with others. This might help the issue with RouteGuidance/RouteGuide implying a ‘step-by-step’ guide is being given.
