### ISSUE TITLE
Route boundaries

### ISSUE THREAD

**Issue by croesus** [openactive/routes#14]
Many routes can be joined at multiple points along the route. It would be useful to be able to search routes by the proximity of not just of their start points, but the boundaries of the route, possibly simplified to a lat/lon bounding box or enclosing circle - see http://www.opensearch.org/Specifications/OpenSearch/Extensions/Geo/1.0/Draft_2

An indexing engine could generate this from the geoPaths, but I wonder whether it's worth modelling the information into the Route Metadata spec

**Comment by thill-odi** [comment]
startPoint is currently an Array, which I think adequately covers the 'multiple points' issue. I'd propose keeping this for Routes rather than Routes Metadata.

**Comment by croesus** [comment]
I hadn't noticed startPoint was an array. That'll work (as long as people are diligent in cataloguing the start points).
