### ISSUE TITLE
National Street Gazetteer 

### ISSUE THREAD

**Issue by walker-EK** [openactive/routes#18]
A broad issue which our head of Public Rights of Way has let me know about: there is a piece of work going on nationally which is the National Street Gazetteer being undertaken by Geoplace         This work is at a very advanced stage apparently and is covering some the same ground i.e. footpaths – suggestion that it would be worth joining up in terms of the standard. 

[](https://www.geoplace.co.uk/streets/managing/what-is-the-nsg)

**Comment by thill-odi** [comment]
Reviewing this, it seems the NSG dataset is not fully open; it's thus difficult to use this in an open-ecosystem project.
