### ISSUE TITLE
Use schema:position

### ISSUE THREAD

**Issue by nickevansuk** [openactive/routes#26]
[`schema:position`](https://schema.org/) should be used instead of `oa:sequence`, as they are functionally identical?

**Comment by thill-odi** [comment]
Right - though useful to constrain to an `Integer` type, and excluding `Text`.

**Comment by nickevansuk** [comment]
Yep, containing schema:position to an integer type is consistent with the booking spec, and also with the broader idea of the OA being based on a subset of schema.org.
