### ISSUE TITLE
'grade' attribute should be renamed 'elevationChange'

### ISSUE THREAD

**Issue by thill-odi** [openactive/routes#4]
The term "grade" could be confused with "difficulty" above

**Comment by croesus** [comment]
`elevationChange` doesn't imply gradient to me. I'd interpret it as the total elevation gained/lost over the course of the route. How about `slope` or `gradient`?

More broadly, I think people would benefit from more than one measure of gradient:
- max gradient (of steepest section)
- total elevation gain (sum of all climbs)
- total elevation loss (sum of all descents)
- average gradient (maybe `avg(abs(gradient))` so up and down slopes don't cancel one another out)

**Comment by thill-odi** [comment]
Renamed 'gradient' in the current specification: https://www.openactive.io/modelling-opportunity-data/EditorsDraft#describing-route-metadata-oa-routemetadata-. For more detail see  https://www.openactive.io/modelling-opportunity-data/EditorsDraft#describing-route-gradients-oa-routegradient-

**Comment by croesus** [comment]
I can see that expressions of gradient might vary, but I'm wondering why totalElevationGain and totalElevationLoss are text, and not simply S.I. (metres) units. Maybe positive for gain and negative for loss.

**Comment by thill-odi** [comment]
@croesus Good catch: the datatype is now `schema:QuantitativeValue` rather than simply `schema:Text`.

I'm wondering about your point about SI measurements. I'm tempted to recommend provision of SI units, as I've only ever seen metres used for this in the wild, and I would imagine many systems are expecting metric measurements. Is there any case for retaining 'feet'?

**Comment by croesus** [comment]
> Is there any case for retaining 'feet'?

I can't think of one. Typically conversions are simple (either on the way in from non-S.I. sources) or on display according to user/cultural preferences). Multiple measurement systems risk confusion and mistakes.

**Comment by thill-odi** [comment]
Okay, then perhaps simplest to make the field simply metres, and populated by an integer.

**Comment by thill-odi** [comment]
Okay, both `totalElevationGain` and `totalElevationLoss` are now defined as integers, with the units being metres.
