### ISSUE TITLE
'duration' attribute should be 'totalDuration'

### ISSUE THREAD

**Issue by thill-odi** [openactive/routes#7]
Because a Route may be made of segments, each of which will have its own duration, the duration of the parent Route should be indicated as 'totalDuration'.

**Comment by croesus** [comment]
I'm comfortable with `duration` being used for routes and segments, but don't feel strongly either way.

Wondering whether durations should be an array and include activity information? Also, since paces vary widely perhaps the correct term is `indicativeDuration` e.g.

```
indicativeDurations : [
 { activity: "walking", duration: 7200 },
 { activity: "cycling", duration: 2400 },
 { activity: "running", duration: 3600 }
]
```

**Comment by thill-odi** [comment]
Left as 'duration', but modelled as an array as suggested. See https://www.openactive.io/modelling-opportunity-data/EditorsDraft#describing-route-metadata-oa-routemetadata-.
