### ISSUE TITLE
mapReference needs to support references other than Ordnance Survey

### ISSUE THREAD

**Issue by thill-odi** [openactive/routes#8]
Is OS too UK-specific? Maybe a complex type with the grid name e.g. OSGB36 and the reference, or even an array of such types if there's more than one grid available

**Comment by blabyboy** [comment]
I think Lat/Lng (WGS84) would be better, it's a worldwide standard and leaves it available for non-UK specific entities to also use the data. Or, having the ability to define different Spatial Reference Systems(SRS) would be useful. Flexibility is the key, locking into one SRS seems a mistake.

**Comment by thill-odi** [comment]
@blabyboy: I like the idea of being able to use different SRSs ... particularly as I'm sure we'll find this in the data. But I'm afraid I'm too much of a geoN00b to know how to support this. Leaving WGS84 to the side for the moment (I think lat/long should be supported, but in separate attributes), could this be as simple as:

reference:[grid reference]
spatialReferenceSystem:[name of system]

**Comment by blabyboy** [comment]
On further investigation, I'd revise my earlier suggestion and push for WGS84 based on that SRS being used for both GPX(mentioned in other materials) and GeoJSON standards of representing geo-data. 

See:
https://tools.ietf.org/html/rfc7946#section-4  (GeoJSON)
and 
https://www.topografix.com/GPX/1/1/#type_latitudeType  (GPX)

So my revised suggestion would be to fix on WGS84 and leave it to the consumer to convert to OSGB36 if needed for their data storage systems.
* This removes the need for a complex type;
* It keeps to a common SRS used by other geo-related publishing standards (notably GeoJSON and GPX).

**Comment by thill-odi** [comment]
@blabyboy: I think the problem is less data-storage systems (though that might be the case too) than end-user consumption. If I look at e.g. walks from the [National Trust](https://www.nationaltrust.org.uk/carding-mill-valley-and-the-shropshire-hills/trails/a-walk-to-the-waterfall-at-carding-mill-valley) or [Explore Kent](https://explorekent.org/activities/cuxton-rail-trail-walk/), I find OS references. I can see your point about supporting the most fundamental and universal reference system - but I think this points to a need to support multiple types rather than simply (from a certain perspective) the best or most widely applicable.

**Comment by thill-odi** [comment]
See https://www.openactive.io/modelling-opportunity-data/EditorsDraft#describing-map-references-oa-mapreference- for the current approach.
