### ISSUE TITLE
Describing Difficulty and Suitability

### ISSUE THREAD

**Issue by thill-odi** [openactive/routes#9]
One topic touched on at the workshop was how to describe the difficulty of a path, or its suitability for various groups. There has been an [extensive discussion](https://github.com/openactive/modelling-opportunity-data/issues/82) of this in relation to the Opportunity specification, but Routes seems a different case; while an activity provider may arbitrarily declare, say, a yoga class to be 'Easy/Intermediate/Advanced', the characteristics of Routes are more 'objective'.

One possibility raised in the workshop was that no difficulty level should be provided at all, on the basis that individuals vary widely and information such as e.g. gradient and distance should simply be provided in the expectation that they can make these judgements for themselves. Alternatively, however, it was suggested that novice or inexperienced Routes users - that is to say, precisely the group OpenActive is aiming to target - are poorly placed to make these kinds of judgements.

A [quick survey](https://docs.google.com/spreadsheets/d/12hAkSB9OP3snzzRj9TKwod-1yVYRECkLBk4garIWDPw/edit#gid=0) of Routes-publishing organisations indicates a variety of terms and practices here, ranging from no rating, through simple and informal gradations, to well-developed taxonomies (e.g. from [British Cycling](https://www.britishcycling.org.uk/search/article/mtbst20100615-MTB-Trail-Grading-System-0))

**Comment by thill-odi** [comment]
For one approach, see the Difficulty sheet here: https://docs.google.com/spreadsheets/d/1vNpt5eBW6WeF3VKy0sE1Ca69RXgvXWys6lyaHkaudOE/edit#gid=548536926

**Comment by Gill-nwuk** [comment]
We have tried so many things over the years but have come to the conclusion that terms like easy or challenging mean different things to different folk. Apart from distance and estimated time to complete a walk, we have recently trialled adding the following, gradient (via gpx outline), terrain (i.e how is it underfoot as things like camber, sand or scree can make a short walk tough!) and finally the pace if it is a  led group walk. Clearly this leads to having sub grades for each  of these elements but it has massively helped us avoid people turning up on unsuitable walks.

**Comment by thill-odi** [comment]
@Gill-nwuk: I'm interested by your mention of 'having sub grades for each of these elements'. Does this mean you have a controlled vocabulary or taxonomy for these things? And if you do, would it be possible to share it?

**Comment by thill-odi** [comment]
See https://www.openactive.io/modelling-opportunity-data/EditorsDraft#describing-route-difficulty-oa-routedifficulty- for the current approach.

**Comment by abs0** [comment]
While novice route users may be poorly placed to make judgements from metric data such as gradient, distance and footing, presumably we would not expect them to directly consume raw oa data, so the question would be more one of providing  separate general advice on how to present and recommend routes based on the metrics. The advice could be updated over time independent to the oa data.

Having said that I think it might make sense to have an optional free text description of the difficulty/suitability of a given route so organisations which already have such data can populate it

**Comment by abs0** [comment]
It feels like this is an aspect which combines well with route segments #10 - many well known routes can have quite different characteristics in different segments

**Comment by thill-odi** [comment]
Okay, the possibility of unpacking raw gradient, distance, etc data into difficulty information I think is well catered for by the `difficultyDescription` and `difficultyDefinitionURL` fields (http://localhost:4000/EditorsDraft/index.html#describing-route-difficulty-oa-routedifficulty-). The remaining TODO is then to give guidance on how best to populate these fields.
